export const demoMobilesListData = [
  {
    id: 1,
    image: "/mobileimg1.webp",
    price: "Rs 180,000",
    brand: "vivo",
    condition: "new",
    title: "Apple iPhone 12 Pro Max 256GB PTA For Sale",
    location: "Nai Abadi, Sahiwal",
    featured: true,
    time: "1 day ago",
    desc: `It is a long established fact that a reader will be distracted by the readable content of 
    a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal 
    distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.`,
    userDetails: [
      {
        name: "John",
        contact: "92123456789",
        location: "Nai Abadi, Sahiwal",
        memberSince: "December 2021",
      },
    ],
  },
  {
    id: 2,
    image: "/mobileimg2.webp",
    price: "Rs 220,000",
    brand: "Samsung",
    condition: "new",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
    desc: `This Samsung Galaxy S22 Ultra is brand new, sealed pack. Warranty available. No scratches, perfect condition.`,
    userDetails: [
      {
        name: "Ali",
        contact: "92345678901",
        location: "Gulberg, Lahore",
        memberSince: "January 2023",
      },
    ],
  },
  {
    id: 3,
    image: "/mobileimg3.webp",
    price: "Rs 95,000",
    brand: "OnePlus",
    condition: "used",
    title: "OnePlus 9R - Lightly Used",
    location: "Johar Town, Lahore • 2 weeks ago",
    featured: true,
    desc: `Lightly used OnePlus 9R in excellent condition. No dents or scratches. Charger and box included.`,
    userDetails: [
      {
        name: "Sara",
        contact: "923112223334",
        location: "Johar Town, Lahore",
        memberSince: "July 2022",
      },
    ],
  },
  {
    id: 4,
    image: "/mobileimg4.webp",
    price: "Rs 220,000",
    brand: "Samsung",
    condition: "new",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
    desc: `Brand new Samsung Galaxy S22 Ultra. Warranty card and all accessories available.`,
    userDetails: [
      {
        name: "Usman",
        contact: "923000112233",
        location: "Gulberg, Lahore",
        memberSince: "March 2022",
      },
    ],
  },
  {
    id: 5,
    image: "/mobileimg5.webp",
    price: "Rs 180,000",
    brand: "Apple",
    condition: "used",
    title: "Apple iPhone 12 Pro Max 256GB PTA For Sale",
    location: "Nai Abadi, Sahiwal • 1 week ago",
    featured: true,
    desc: `Used iPhone 12 Pro Max. Minor scratch on back. Battery health 90%. PTA approved.`,
    userDetails: [
      {
        name: "Ayesha",
        contact: "923451234567",
        location: "Sahiwal",
        memberSince: "November 2021",
      },
    ],
  },
  {
    id: 6,
    image: "/mobileimg6.webp",
    price: "Rs 220,000",
    brand: "Samsung",
    condition: "new",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
    desc: `Samsung Galaxy S22 Ultra, never used. 12GB RAM, 256GB storage. Black color.`,
    userDetails: [
      {
        name: "Fahad",
        contact: "923123456789",
        location: "Gulberg, Lahore",
        memberSince: "August 2023",
      },
    ],
  },
  {
    id: 7,
    image: "/mobileimg7.webp",
    price: "Rs 95,000",
    brand: "OnePlus",
    condition: "used",
    title: "OnePlus 9R - Lightly Used",
    location: "Johar Town, Lahore • 2 weeks ago",
    featured: true,
    desc: `OnePlus 9R used for 6 months. With box, charger, and silicone case.`,
    userDetails: [
      {
        name: "Zain",
        contact: "923090909090",
        location: "Johar Town, Lahore",
        memberSince: "February 2023",
      },
    ],
  },
  {
    id: 8,
    image: "/mobileimg8.webp",
    price: "Rs 220,000",
    brand: "Samsung",
    condition: "new",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
    desc: `Latest model Samsung Galaxy. Original accessories included. No trade offers, please.`,
    userDetails: [
      {
        name: "Hira",
        contact: "923321112233",
        location: "Gulberg, Lahore",
        memberSince: "May 2022",
      },
    ],
  },
  {
    id: 9,
    image: "/mobileimg9.webp",
    price: "Rs 220,000",
    brand: "Samsung",
    condition: "new",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
    desc: `Unopened box of Samsung Galaxy S22 Ultra. Dual SIM. Delivery available in Lahore.`,
    userDetails: [
      {
        name: "Kamran",
        contact: "923456700000",
        location: "Lahore",
        memberSince: "October 2023",
      },
    ],
  },
  {
    id: 10,
    image: "/mobileimg10.webp",
    price: "Rs 220,000",
    brand: "Samsung",
    condition: "new",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
    desc: `Sealed pack S22 Ultra. PTA approved, 1 year warranty. Official accessories included.`,
    userDetails: [
      {
        name: "Nadia",
        contact: "923456789123",
        location: "Lahore",
        memberSince: "June 2022",
      },
    ],
  },
];
