export const demoMobilesListData = [
  {
    id: 1,
    image: "/mobileimg1.webp",
    price: "Rs 180,000",
    title: "Apple iPhone 12 Pro Max 256GB PTA For Sale",
    location: "Nai Abadi, Sahiwal",
    featured: true,
    desc: `It is a long established fact that a reader will be distracted by the readable content of 
    a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal 
    distribution of letters, 
    as opposed to using 'Content here, content here', making it look like readable English`,
    userDetails: [
      { name: "John", contact: "92123456789", location: "Nai Abadi, Sahiwal" },
    ],
  },
  {
    id: 2,
    image: "/mobileimg2.webp",
    price: "Rs 220,000",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
  },
  {
    id: 3,
    image: "/mobileimg3.webp",
    price: "Rs 95,000",
    title: "OnePlus 9R - Lightly Used",
    location: "Johar Town, Lahore • 2 weeks ago",
    featured: true,
  },
  {
    id: 4,
    image: "/mobileimg4.webp",
    price: "Rs 220,000",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
  },
  {
    id: 5,
    image: "/mobileimg5.webp",
    price: "Rs 180,000",
    title: "Apple iPhone 12 Pro Max 256GB PTA For Sale",
    location: "Nai Abadi, Sahiwal • 1 week ago",
    featured: true,
  },
  {
    id: 6,
    image: "/mobileimg6.webp",
    price: "Rs 220,000",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
  },
  {
    id: 7,
    image: "/mobileimg7.webp",
    price: "Rs 95,000",
    title: "OnePlus 9R - Lightly Used",
    location: "Johar Town, Lahore • 2 weeks ago",
    featured: true,
  },
  {
    id: 8,
    image: "/mobileimg8.webp",
    price: "Rs 220,000",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
  },
  {
    id: 9,
    image: "/mobileimg9.webp",
    price: "Rs 220,000",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
  },
  {
    id: 10,
    image: "/mobileimg10.webp",
    price: "Rs 220,000",
    title: "Samsung Galaxy S22 Ultra - Brand New",
    location: "Gulberg, Lahore • 3 days ago",
    featured: true,
  },
];
